// This file is auto-generated by scripts/generate-posts.ts
// Do not edit manually

export const postsData: Record<string, string> = {
  '3D-Image-Tracing': `---
name: "3D-Image-Tracing"
category: "Tracing"
image: "/img/FirstAssignment-01.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>First I create a fish image using  tracing and after that I add 3D effect on this Image.</p>`,
  'Clock': `---
name: "Clock"
category: "Tracing"
image: "/img/clockAssignment-01.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I create this image myself using ecllips tool.</p>`,
  'Edit-Image': `---
name: "Edit-Image"
category: "Editing"
image: "/img/acnefaceAssignmet.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I get this photo from google and remove its acne using healing brush tool.</p>`,
  'Flyer': `---
name: "Flyer"
category: "Poster Design"
image: "/img/assignment4.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I create this flyer using adobe illustrator. I use pen tool to make crown. I use polygon tool to create price badge. I use type tool to write on this flyer.</p>`,
  'Logo-On-Mockup': `---
name: "Logo-On-Mockup"
category: "Editing"
image: "/img/logoOnMockupAssignment.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I get this mockup from freepik and apply my created logo using object selection tool on this mockup.</p>`,
  'MH-Logo': `---
name: "MH-Logo"
category: "Logo Design"
image: "/img/mhlogo.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I create this logo using pen tool.</p>`,
  'Photo-Edit': `---
name: "Photo-Edit"
category: "Editing"
image: "/img/editingAssignment.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p></p>`,
  'Poster-2': `---
name: "Poster-2"
category: "Poster Design"
image: "/img/assignment2.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I use pen tool for all designing in this poster. I use type tool to write content on it. I use circle tool to make points for list.</p>`,
  'Poster': `---
name: "Poster"
category: "Poster Design"
image: "/img/assignmentPoster-01.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I use pen tool for all designing in this poster. I use type tool to write content on it. I use star tool to make stars for list points.</p>`,
  'Repair-Image': `---
name: "Repair-Image"
category: "Editing"
image: "/img/redeyesAssignment.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I get this photo from google and repair it using red eye tool to shows eyes normal.</p>`,
  'Saloon-Logo': `---
name: "Saloon-Logo"
category: "Logo Design"
image: "/img/assignment6.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I create this logo using pen tool and Write text using type tool.</p>`,
  'School-Logo-2': `---
name: "School-Logo-2"
category: "Logo Design"
image: "/img/LOGO_DESIGN.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I create this logo using pen tool and Write text using type tool. I use ellipse tool to make its boundaries.</p>`,
  'School-Logo': `---
name: "School-Logo"
category: "Logo Design"
image: "/img/assignment5.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I create this logo using pen tool and Write text using type tool.</p>`,
  'Social-Media-Post': `---
name: "Social-Media-Post"
category: "Poster Design"
image: "/img/assignment3.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I create this social media post using adobe illustrator. I use mash tool to make mixture of colors in background. I use type tool to write content on this post.</p>`,
  'Tracing-Image': `---
name: "Tracing-Image"
category: "Tracing"
image: "/img/tracingAssignment.jpg"
---

<h2 class='text-xl font-bold'>Description</h2>
<br>
<p>I get Pikachu image from google and use pen tool to trace this image.</p>`,
};
